import { ref } from 'vue'

export function useEventCard() {
    const eventCards = ref([
        {
            id: 1,
            category: 'technology',
            title_en: 'Tech Conference 2024',
            title_da: 'Tech Konference 2024',
            title_de: 'Tech Konferenz 2024',
            date: '2026-06-06',
            location_en: 'Copenhagen, Denmark',
            location_da: 'København, Danmark',
            location_de: 'Kopenhagen, Dänemark',
            category_en: 'Technology',
            category_da: 'Teknologi',
            category_de: 'Technologie',
            image: 'https://i.imgur.com/AXmyIBs.jpeg',
            slug: 'tech-conference-2024',
        },
        {
            id: 2,
            category: 'business',
            title_en: 'Business Summit',
            title_da: 'Erhvervsmøde',
            title_de: 'Geschäftsgipfel',
            date: '2026-06-13',
            location_en: 'Aarhus, Denmark',
            location_da: 'Aarhus, Danmark',
            location_de: 'Aarhus, Dänemark',
            category_en: 'Business',
            category_da: 'Erhverv',
            category_de: 'Geschäft',
            image: 'https://i.imgur.com/AXmyIBs.jpeg',
            slug: 'business-summit',
        },
        {
            id: 3,
            category: 'workshop',
            title_en: 'Innovation Workshop',
            title_da: 'Innovationsworkshop',
            title_de: 'Innovations-Workshop',
            date: '2026-06-20',
            location_en: 'Hamburg, Germany',
            location_da: 'Hamburg, Tyskland',
            location_de: 'Hamburg, Deutschland',
            category_en: 'Workshop',
            category_da: 'Workshop',
            category_de: 'Workshop',
            image: 'https://i.imgur.com/AXmyIBs.jpeg',
            slug: 'innovation-workshop',
        },
        {
            id: 4,
            category: 'networking',
            title_en: 'Networking Dinner',
            title_da: 'Netværksmiddag',
            title_de: 'Netzwerk-Dinner',
            date: '2026-06-27',
            location_en: 'Berlin, Germany',
            location_da: 'Berlin, Tyskland',
            location_de: 'Berlin, Deutschland',
            category_en: 'Networking',
            category_da: 'Netværk',
            category_de: 'Netzwerk',
            image: 'https://i.imgur.com/AXmyIBs.jpeg',
            slug: 'networking-dinner',
        },
        {
            id: 5,
            category: 'trade-fair',
            title_en: 'Trade Fair 2026',
            title_da: 'Handelsmesse 2026',
            title_de: 'Handelsmesse 2026',
            date: '2026-07-04',
            location_en: 'Copenhagen, Denmark',
            location_da: 'København, Danmark',
            location_de: 'Kopenhagen, Dänemark',
            category_en: 'Trade Fair',
            category_da: 'Handelsmesse',
            category_de: 'Handelsmesse',
            image: 'https://i.imgur.com/AXmyIBs.jpeg',
            slug: 'trade-fair-2026',
        },
        {
            id: 6,
            category: 'leadership',
            title_en: 'Leadership Conference',
            title_da: 'Ledelseskonference',
            title_de: 'Führungskonferenz',
            date: '2026-07-11',
            location_en: 'Hamburg, Germany',
            location_da: 'Hamburg, Tyskland',
            location_de: 'Hamburg, Deutschland',
            category_en: 'Leadership',
            category_da: 'Ledelse',
            category_de: 'Führung',
            image: 'https://i.imgur.com/AXmyIBs.jpeg',
            slug: 'leadership-conference',
        },
        {
            id: 7,
            category: 'marketing',
            title_en: 'Digital Marketing Seminar',
            title_da: 'Digital Markedsføring Seminar',
            title_de: 'Digital-Marketing-Seminar',
            date: '2026-07-18',
            location_en: 'Aarhus, Denmark',
            location_da: 'Aarhus, Danmark',
            location_de: 'Aarhus, Dänemark',
            category_en: 'Marketing',
            category_da: 'Markedsføring',
            category_de: 'Marketing',
            image: 'https://i.imgur.com/AXmyIBs.jpeg',
            slug: 'digital-marketing-seminar',
        },
        {
            id: 8,
            category: 'startup',
            title_en: 'Startup Pitch Event',
            title_da: 'Startup Pitch Arrangement',
            title_de: 'Startup Pitch Veranstaltung',
            date: '2026-07-25',
            location_en: 'Berlin, Germany',
            location_da: 'Berlin, Tyskland',
            location_de: 'Berlin, Deutschland',
            category_en: 'Startup',
            category_da: 'Startup',
            category_de: 'Startup',
            image: 'https://i.imgur.com/AXmyIBs.jpeg',
            slug: 'startup-pitch-event',
        },
    ])

    return {
        eventCards,
    }
}
