import { ref, computed } from 'vue'

export const useNetwork = () => {
    const members = ref([
        {
            id: 1,
            slug: "agentur-fur-arbeit-flensburg",
            name: "Agentur für Arbeit Flensburg",
            description: "Public employment agency for the Flensburg region.",
            description_da: "Offentligt arbejdsformidlingskontor for Flensborg-regionen.",
            description_de: "Öffentliche Arbeitsagentur für die Region Flensburg.",
            descriptionLong: "Agentur für Arbeit Flensburg is the public employment agency serving the Flensburg region. We support both jobseekers and employers with recruitment, training, and labour market consulting across Northern Germany.",
            descriptionLong_da: "Agentur für Arbeit Flensburg er det offentlige arbejdsformidlingskontor for Flensborg-regionen. Vi støtter både jobsøgende og arbejdsgivere med rekruttering, uddannelse og arbejdsmarkedsrådgivning i hele Nordtyskland.",
            descriptionLong_de: "Die Agentur für Arbeit Flensburg ist die öffentliche Arbeitsagentur für die Region Flensburg. Wir unterstützen sowohl Arbeitssuchende als auch Arbeitgeber mit Vermittlung, Weiterbildung und Arbeitsmarktberatung in ganz Norddeutschland.",
            country: "DE",
            image: "https://imgur.com/9IXPg5L.jpeg",
            website: "www.arbeitsagentur.de",
            phone: "+49 461 8190",
            address: "Waldemar-Petersen-Straße 3, 24943 Flensburg",
            email: "flensburg@arbeitsagentur.de"
        },
        {
            id: 2,
            slug: "bundesagentur-fur-arbeit",
            name: "Bundesagentur für Arbeit",
            description: "German federal employment agency supporting jobseekers and employers.",
            description_da: "Tysk forbundsarbejdsformidling, der støtter jobsøgende og arbejdsgivere.",
            description_de: "Deutsche Bundesagentur für Arbeit zur Unterstützung von Arbeitssuchenden und Arbeitgebern.",
            descriptionLong: "Bundesagentur für Arbeit is Germany's federal employment authority, supporting jobseekers and employers across the country. We provide labour market analysis, recruitment services, and integration programs nationwide.",
            descriptionLong_da: "Bundesagentur für Arbeit er Tysklands forbundsarbejdsmarkedsmyndighed, der støtter jobsøgende og arbejdsgivere i hele landet. Vi leverer arbejdsmarkedsanalyser, rekrutteringstjenester og integrationsprogrammer på landsplan.",
            descriptionLong_de: "Die Bundesagentur für Arbeit ist die deutsche Bundesbehörde für Arbeit und unterstützt Arbeitssuchende und Arbeitgeber im ganzen Land. Wir bieten Arbeitsmarktanalysen, Vermittlungsdienste und Integrationsprogramme bundesweit an.",
            country: "DE",
            image: "https://imgur.com/gVVRTN7.jpeg",
            website: "www.arbeitsagentur.de",
            phone: "+49 911 1790",
            address: "Regensburger Straße 104, 90478 Nürnberg",
            email: "zentrale@arbeitsagentur.de"
        },
        {
            id: 3,
            slug: "business-aabenraa",
            name: "Business Aabenraa",
            description: "Business council supporting companies and growth in Aabenraa.",
            description_da: "Erhvervsråd, der støtter virksomheder og vækst i Aabenraa.",
            description_de: "Wirtschaftsrat zur Förderung von Unternehmen und Wachstum in Apenrade.",
            descriptionLong: "Business Aabenraa is the official business council for Aabenraa Municipality, supporting local companies with growth strategies, networking, and access to international markets across the Danish-German cross-border region.",
            descriptionLong_da: "Business Aabenraa er det officielle erhvervsråd for Aabenraa Kommune, som støtter lokale virksomheder med vækststrategier, netværk og adgang til internationale markeder i den dansk-tyske grænseregion.",
            descriptionLong_de: "Business Aabenraa ist der offizielle Wirtschaftsrat der Gemeinde Apenrade und unterstützt lokale Unternehmen mit Wachstumsstrategien, Networking und Zugang zu internationalen Märkten in der deutsch-dänischen Grenzregion.",
            country: "DK",
            image: "https://imgur.com/kQLqblw.jpeg",
            website: "www.businessaabenraa.dk",
            phone: "+45 73 76 76 76",
            address: "Skelbækvej 2, 6200 Aabenraa",
            email: "info@businessaabenraa.dk"
        },
        {
            id: 4,
            slug: "business-esbjerg",
            name: "Business Esbjerg",
            description: "Business council supporting companies and growth in Esbjerg.",
            description_da: "Erhvervsråd, der støtter virksomheder og vækst i Esbjerg.",
            description_de: "Wirtschaftsrat zur Förderung von Unternehmen und Wachstum in Esbjerg.",
            descriptionLong: "Business Esbjerg is the official business council for Esbjerg Municipality, supporting local companies with growth strategies, networking, and international expansion. We connect businesses across Denmark's leading energy hub and the Danish-German cross-border region.",
            descriptionLong_da: "Business Esbjerg er det officielle erhvervsråd for Esbjerg Kommune, som støtter lokale virksomheder med vækststrategier, netværk og international ekspansion. Vi forbinder virksomheder på tværs af Danmarks førende energiknudepunkt og den dansk-tyske grænseregion.",
            descriptionLong_de: "Business Esbjerg ist der offizielle Wirtschaftsrat der Gemeinde Esbjerg und unterstützt lokale Unternehmen mit Wachstumsstrategien, Networking und internationaler Expansion. Wir verbinden Unternehmen über Dänemarks führendes Energiezentrum und die deutsch-dänische Grenzregion hinweg.",
            country: "DK",
            image: "https://imgur.com/IDfDBmc.jpeg",
            website: "www.businessesbjerg.com",
            phone: "+45 71 31 19 09",
            address: "Gronnegade 21, 6700 Esbjerg",
            email: "info@businessesbjerg.dk"
        },
        {
            id: 5,
            slug: "business-kolding",
            name: "Business Kolding",
            description: "Business council supporting companies and growth in Kolding.",
            description_da: "Erhvervsråd, der støtter virksomheder og vækst i Kolding.",
            description_de: "Wirtschaftsrat zur Förderung von Unternehmen und Wachstum in Kolding.",
            descriptionLong: "Business Kolding is the official business council for Kolding Municipality, helping companies with entrepreneurship, design innovation, and cross-border collaboration across Southern Denmark and Northern Germany.",
            descriptionLong_da: "Business Kolding er det officielle erhvervsråd for Kolding Kommune, som hjælper virksomheder med iværksætteri, designinnovation og grænseoverskridende samarbejde på tværs af Syddanmark og Nordtyskland.",
            descriptionLong_de: "Business Kolding ist der offizielle Wirtschaftsrat der Gemeinde Kolding und unterstützt Unternehmen bei Existenzgründung, Designinnovation und grenzüberschreitender Zusammenarbeit in Süddänemark und Norddeutschland.",
            country: "DK",
            image: "https://imgur.com/ALgvHRT.jpeg",
            website: "www.businesskolding.dk",
            phone: "+45 76 30 06 90",
            address: "Akseltorv 1, 6000 Kolding",
            email: "info@businesskolding.dk"
        },
        {
            id: 6,
            slug: "copenhagen-capacity",
            name: "Copenhagen Capacity",
            description: "Investment promotion agency attracting companies and talent to Greater Copenhagen.",
            description_da: "Investeringsfremmeorganisation, der tiltrækker virksomheder og talenter til Greater Copenhagen.",
            description_de: "Investitionsförderungsagentur, die Unternehmen und Talente in den Großraum Kopenhagen zieht.",
            descriptionLong: "Copenhagen Capacity is the official investment promotion agency for Greater Copenhagen, attracting foreign companies and international talent to establish themselves in the Danish capital region.",
            descriptionLong_da: "Copenhagen Capacity er den officielle investeringsfremmeorganisation for Greater Copenhagen, som tiltrækker udenlandske virksomheder og internationale talenter til at etablere sig i den danske hovedstadsregion.",
            descriptionLong_de: "Copenhagen Capacity ist die offizielle Investitionsförderungsagentur für den Großraum Kopenhagen und zieht ausländische Unternehmen und internationale Talente an, um sich in der dänischen Hauptstadtregion niederzulassen.",
            country: "DK",
            image: "https://imgur.com/MoBQJh7.jpeg",
            website: "www.copcap.com",
            phone: "+45 33 22 02 22",
            address: "Nørregade 7B, 1165 København K",
            email: "info@copcap.com"
        },
        {
            id: 7,
            slug: "di-dansk-industri-deutschland",
            name: "DI – Dansk Industri Deutschland",
            description: "The German branch of the Confederation of Danish Industry.",
            description_da: "Den tyske afdeling af Dansk Industri.",
            description_de: "Die deutsche Niederlassung des Verbandes der dänischen Industrie.",
            descriptionLong: "DI – Dansk Industri Deutschland is the German office of the Confederation of Danish Industry, supporting Danish companies looking to enter, grow, or operate in the German market.",
            descriptionLong_da: "DI – Dansk Industri Deutschland er Dansk Industris tyske kontor, som støtter danske virksomheder, der ønsker at komme ind på, vokse i eller operere på det tyske marked.",
            descriptionLong_de: "DI – Dansk Industri Deutschland ist das deutsche Büro des Verbandes der dänischen Industrie und unterstützt dänische Unternehmen, die in den deutschen Markt eintreten, wachsen oder dort tätig sein möchten.",
            country: "DE",
            image: "https://imgur.com/ZA9ssRs.jpeg",
            website: "www.danskindustri.de",
            phone: "+49 30 5900 9970",
            address: "Reinhardtstraße 32, 10117 Berlin",
            email: "berlin@di.dk"
        },
        {
            id: 8,
            slug: "foreningen-sonderborg-vaekstrad",
            name: "Foreningen Sønderborg Vækstråd",
            description: "Growth council supporting companies in Sønderborg Municipality.",
            description_da: "Vækstråd, der støtter virksomheder i Sønderborg Kommune.",
            description_de: "Wachstumsrat zur Förderung von Unternehmen in der Gemeinde Sonderburg.",
            descriptionLong: "Foreningen Sønderborg Vækstråd is the growth council for Sønderborg Municipality, supporting local companies with consulting, networking, and regional development across Southern Denmark.",
            descriptionLong_da: "Foreningen Sønderborg Vækstråd er vækstrådet for Sønderborg Kommune, som støtter lokale virksomheder med rådgivning, netværk og regional udvikling i Syddanmark.",
            descriptionLong_de: "Der Sonderburg Wachstumsrat ist der Wachstumsrat der Gemeinde Sonderburg und unterstützt lokale Unternehmen mit Beratung, Networking und Regionalentwicklung in Süddänemark.",
            country: "DK",
            image: "https://imgur.com/zyXtkSe.jpeg",
            website: "www.sonderborgvaekstraad.dk",
            phone: "+45 88 72 50 00",
            address: "Rådhustorvet 10, 6400 Sønderborg",
            email: "info@sonderborgvaekstraad.dk"
        },
        {
            id: 9,
            slug: "hansebelt-ev",
            name: "HanseBelt e.V.",
            description: "German business network promoting Danish-German cooperation in the Fehmarnbelt region.",
            description_da: "Tysk erhvervsnetværk, der fremmer dansk-tysk samarbejde i Femern Bælt-regionen.",
            description_de: "Deutsches Wirtschaftsnetzwerk zur Förderung der deutsch-dänischen Zusammenarbeit in der Fehmarnbelt-Region.",
            descriptionLong: "HanseBelt e.V. is a German business association promoting cross-border cooperation in the Fehmarnbelt region. We bring together companies from Northern Germany and Denmark to develop the area around the future Fehmarn tunnel.",
            descriptionLong_da: "HanseBelt e.V. er en tysk erhvervsforening, der fremmer grænseoverskridende samarbejde i Femern Bælt-regionen. Vi samler virksomheder fra Nordtyskland og Danmark for at udvikle området omkring den kommende Femern-tunnel.",
            descriptionLong_de: "HanseBelt e.V. ist ein deutscher Wirtschaftsverband zur Förderung der grenzüberschreitenden Zusammenarbeit in der Fehmarnbelt-Region. Wir bringen Unternehmen aus Norddeutschland und Dänemark zusammen, um das Gebiet rund um den künftigen Fehmarnbelttunnel zu entwickeln.",
            country: "DE",
            image: "https://imgur.com/gMF7sdX.jpeg",
            website: "www.hansebelt.de",
            phone: "+49 451 7060140",
            address: "Falkenstraße 11, 23564 Lübeck",
            email: "info@hansebelt.de"
        },
        {
            id: 10,
            slug: "jackstadt-zentrum-flensburg",
            name: "Jackstädt-Zentrum Flensburg",
            description: "Entrepreneurship and innovation centre at Hochschule Flensburg.",
            description_da: "Iværksætter- og innovationscenter ved Hochschule Flensburg.",
            description_de: "Gründungs- und Innovationszentrum an der Hochschule Flensburg.",
            descriptionLong: "Jackstädt-Zentrum Flensburg is the entrepreneurship and innovation centre at Hochschule Flensburg. We support startups, students, and entrepreneurs with workshops, mentoring, and cross-border opportunities.",
            descriptionLong_da: "Jackstädt-Zentrum Flensburg er iværksætter- og innovationscentret ved Hochschule Flensburg. Vi støtter startups, studerende og iværksættere med workshops, mentorordninger og grænseoverskridende muligheder.",
            descriptionLong_de: "Das Jackstädt-Zentrum Flensburg ist das Gründungs- und Innovationszentrum an der Hochschule Flensburg. Wir unterstützen Startups, Studierende und Gründer mit Workshops, Mentoring und grenzüberschreitenden Möglichkeiten.",
            country: "DE",
            image: "https://imgur.com/J8U8ARC.jpeg",
            website: "www.jackstaedt-zentrum.de",
            phone: "+49 461 805 1542",
            address: "Kanzleistraße 91-93, 24943 Flensburg",
            email: "info@jackstaedt-zentrum.de"
        },
        {
            id: 11,
            slug: "ihk-zu-flensburg",
            name: "Industrie- und Handelskammer zu Flensburg",
            description: "Chamber of industry and commerce supporting businesses in Schleswig-Holstein.",
            description_da: "Industri- og handelskammer, der støtter virksomheder i Slesvig-Holsten.",
            description_de: "Industrie- und Handelskammer zur Unterstützung von Unternehmen in Schleswig-Holstein.",
            descriptionLong: "Industrie- und Handelskammer zu Flensburg is the chamber of industry and commerce serving businesses in the Flensburg region of Schleswig-Holstein, offering training, certifications, and business advocacy.",
            descriptionLong_da: "Industrie- und Handelskammer zu Flensburg er industri- og handelskammeret, der betjener virksomheder i Flensborg-regionen i Slesvig-Holsten og tilbyder uddannelse, certificeringer og erhvervsinteressevaretagelse.",
            descriptionLong_de: "Die Industrie- und Handelskammer zu Flensburg betreut Unternehmen in der Region Flensburg in Schleswig-Holstein und bietet Weiterbildung, Zertifizierungen und Interessenvertretung für Unternehmen.",
            country: "DE",
            image: "https://imgur.com/yUF5Gpa.jpeg",
            website: "www.ihk-flensburg.de",
            phone: "+49 461 806 0",
            address: "Heinrichstraße 28-34, 24937 Flensburg",
            email: "info@flensburg.ihk.de"
        },
        {
            id: 12,
            slug: "kielregion-gmbh",
            name: "KielRegion GmbH",
            description: "Regional development organisation for the Kiel area in Schleswig-Holstein.",
            description_da: "Regional udviklingsorganisation for Kiel-området i Slesvig-Holsten.",
            description_de: "Regionale Entwicklungsorganisation für die Kieler Region in Schleswig-Holstein.",
            descriptionLong: "KielRegion GmbH is the regional development organisation for the Kiel area, working on economic development, mobility, and regional marketing across Kiel, Plön, and Rendsburg-Eckernförde.",
            descriptionLong_da: "KielRegion GmbH er den regionale udviklingsorganisation for Kiel-området, der arbejder med erhvervsudvikling, mobilitet og regional markedsføring på tværs af Kiel, Plön og Rendsburg-Eckernförde.",
            descriptionLong_de: "Die KielRegion GmbH ist die regionale Entwicklungsorganisation für die Kieler Region und arbeitet an Wirtschaftsförderung, Mobilität und Regionalmarketing in Kiel, Plön und Rendsburg-Eckernförde.",
            country: "DE",
            image: "https://imgur.com/Bgy8NSd.jpeg",
            website: "www.kielregion.de",
            phone: "+49 431 5306 600",
            address: "Hopfenstraße 30, 24103 Kiel",
            email: "info@kielregion.de"
        },
        {
            id: 13,
            slug: "region-syddanmark",
            name: "Region Syddanmark",
            description: "Danish regional authority driving development in Southern Denmark.",
            description_da: "Dansk regional myndighed, der driver udviklingen i Syddanmark.",
            description_de: "Dänische Regionalbehörde, die die Entwicklung in Süddänemark vorantreibt.",
            descriptionLong: "Region Syddanmark is one of Denmark's five administrative regions, covering Southern Denmark. We drive regional development, healthcare, and cross-border cooperation in the Danish-German border region.",
            descriptionLong_da: "Region Syddanmark er en af Danmarks fem administrative regioner og dækker Syddanmark. Vi driver regional udvikling, sundhedsvæsen og grænseoverskridende samarbejde i den dansk-tyske grænseregion.",
            descriptionLong_de: "Die Region Süddänemark ist eine der fünf Verwaltungsregionen Dänemarks und umfasst Süddänemark. Wir fördern Regionalentwicklung, Gesundheitsversorgung und grenzüberschreitende Zusammenarbeit in der deutsch-dänischen Grenzregion.",
            country: "DK",
            image: "https://imgur.com/Kdop213.jpeg",
            website: "www.regionsyddanmark.dk",
            phone: "+45 76 63 10 00",
            address: "Damhaven 12, 7100 Vejle",
            email: "kontakt@rsyd.dk"
        },
        {
            id: 14,
            slug: "regionaldirektion-nord",
            name: "Regionaldirektion Nord",
            description: "German federal employment authority for Northern Germany.",
            description_da: "Tysk forbundsarbejdsmarkedsmyndighed for Nordtyskland.",
            description_de: "Deutsche Bundesarbeitsbehörde für Norddeutschland.",
            descriptionLong: "Regionaldirektion Nord is the northern regional directorate of the German Federal Employment Agency, covering labour market policy for Schleswig-Holstein, Hamburg, and Mecklenburg-Vorpommern.",
            descriptionLong_da: "Regionaldirektion Nord er det nordlige regionale direktorat under den tyske forbundsarbejdsformidling, der dækker arbejdsmarkedspolitik for Slesvig-Holsten, Hamborg og Mecklenburg-Vorpommern.",
            descriptionLong_de: "Die Regionaldirektion Nord ist die nördliche Regionaldirektion der Bundesagentur für Arbeit und deckt die Arbeitsmarktpolitik für Schleswig-Holstein, Hamburg und Mecklenburg-Vorpommern ab.",
            country: "DE",
            image: "https://imgur.com/mTC5qNl.jpeg",
            website: "www.arbeitsagentur.de/vor-ort/rd-n",
            phone: "+49 431 709 0",
            address: "Projensdorfer Straße 82, 24106 Kiel",
            email: "kiel.rd-n@arbeitsagentur.de"
        },
        {
            id: 15,
            slug: "erhvervshus-sydjylland",
            name: "S/I Erhvervshus Sydjylland",
            description: "Business hub supporting companies across Southern Jutland.",
            description_da: "Erhvervshus, der støtter virksomheder i hele Sydjylland.",
            description_de: "Wirtschaftszentrum zur Unterstützung von Unternehmen in ganz Südjütland.",
            descriptionLong: "S/I Erhvervshus Sydjylland is a business hub serving companies across Southern Jutland with consulting, funding access, and growth programs.",
            descriptionLong_da: "S/I Erhvervshus Sydjylland er et erhvervshus, der betjener virksomheder i hele Sydjylland med rådgivning, adgang til finansiering og vækstprogrammer.",
            descriptionLong_de: "S/I Erhvervshus Sydjylland ist ein Wirtschaftszentrum, das Unternehmen in ganz Südjütland mit Beratung, Finanzierungszugang und Wachstumsprogrammen unterstützt.",
            country: "DK",
            image: "https://imgur.com/QhU9npS.jpeg",
            website: "www.ehsj.dk",
            phone: "+45 70 22 00 76",
            address: "Bautavej 1A, 6705 Esbjerg Ø",
            email: "info@ehsj.dk"
        },
        {
            id: 16,
            slug: "tonder-erhvervsrad",
            name: "Tønder Erhvervsråd",
            description: "Business council supporting companies and entrepreneurs in Tønder.",
            description_da: "Erhvervsråd, der støtter virksomheder og iværksættere i Tønder.",
            description_de: "Wirtschaftsrat zur Förderung von Unternehmen und Unternehmern in Tondern.",
            descriptionLong: "Tønder Erhvervsråd is the business council for Tønder Municipality, supporting companies and entrepreneurs in Denmark's southernmost cross-border region.",
            descriptionLong_da: "Tønder Erhvervsråd er erhvervsrådet for Tønder Kommune, som støtter virksomheder og iværksættere i Danmarks sydligste grænseregion.",
            descriptionLong_de: "Tønder Erhvervsråd ist der Wirtschaftsrat der Gemeinde Tondern und unterstützt Unternehmen und Unternehmer in der südlichsten Grenzregion Dänemarks.",
            country: "DK",
            image: "https://imgur.com/0GOAs4b.jpeg",
            website: "www.tondererhvervsraad.dk",
            phone: "+45 74 92 92 92",
            address: "Vestergade 9, 6270 Tønder",
            email: "info@tondererhvervsraad.dk"
        },
        {
            id: 17,
            slug: "trekantomradet-danmark",
            name: "Trekantområdet Danmark",
            description: "Regional partnership of seven municipalities in the Triangle Region.",
            description_da: "Regionalt partnerskab mellem syv kommuner i Trekantområdet.",
            description_de: "Regionale Partnerschaft von sieben Gemeinden in der Dreieck-Region.",
            descriptionLong: "Trekantområdet Danmark is the regional partnership of seven municipalities forming Denmark's Triangle Region, coordinating business development and infrastructure projects.",
            descriptionLong_da: "Trekantområdet Danmark er det regionale partnerskab mellem syv kommuner, der udgør Danmarks Trekantområde, og koordinerer erhvervsudvikling og infrastrukturprojekter.",
            descriptionLong_de: "Trekantområdet Danmark ist die regionale Partnerschaft von sieben Gemeinden, die Dänemarks Dreieck-Region bilden, und koordiniert Wirtschaftsentwicklung und Infrastrukturprojekte.",
            country: "DK",
            image: "https://imgur.com/LFQs9Rt.jpeg",
            website: "www.trekantomraadet.dk",
            phone: "+45 79 79 79 79",
            address: "Kolding Åpark 1, 6000 Kolding",
            email: "info@trekantomraadet.dk"
        },
        {
            id: 18,
            slug: "udviklingsrad-sonderjylland",
            name: "Udviklingsråd Sønderjylland",
            description: "Development council for the Sønderjylland region.",
            description_da: "Udviklingsråd for Sønderjylland-regionen.",
            description_de: "Entwicklungsrat für die Region Sonderjütland.",
            descriptionLong: "Udviklingsråd Sønderjylland coordinates development initiatives across the Sønderjylland region, focusing on cross-border collaboration with Schleswig-Holstein.",
            descriptionLong_da: "Udviklingsråd Sønderjylland koordinerer udviklingsinitiativer på tværs af Sønderjylland-regionen med fokus på grænseoverskridende samarbejde med Slesvig-Holsten.",
            descriptionLong_de: "Der Entwicklungsrat Sonderjütland koordiniert Entwicklungsinitiativen in der gesamten Region Sonderjütland mit Schwerpunkt auf der grenzüberschreitenden Zusammenarbeit mit Schleswig-Holstein.",
            country: "DK",
            image: "https://imgur.com/oXZgb4r.jpeg",
            website: "www.udviklingsraadsonderjylland.dk",
            phone: "+45 74 36 80 00",
            address: "Storegade 17, 6200 Aabenraa",
            email: "info@urs.dk"
        },
        {
            id: 19,
            slug: "udviklingsrad-vejen",
            name: "Udviklingsråd Vejen",
            description: "Development council for Vejen Municipality.",
            description_da: "Udviklingsråd for Vejen Kommune.",
            description_de: "Entwicklungsrat für die Gemeinde Vejen.",
            descriptionLong: "Udviklingsråd Vejen is the development council for Vejen Municipality, supporting local business growth and community development in Southern Denmark.",
            descriptionLong_da: "Udviklingsråd Vejen er udviklingsrådet for Vejen Kommune, som støtter lokal erhvervsvækst og samfundsudvikling i Syddanmark.",
            descriptionLong_de: "Der Entwicklungsrat Vejen ist der Entwicklungsrat der Gemeinde Vejen und unterstützt lokales Unternehmenswachstum und Gemeindeentwicklung in Süddänemark.",
            country: "DK",
            image: "https://imgur.com/bYugwXa.jpeg",
            website: "www.urvejen.dk",
            phone: "+45 79 96 50 00",
            address: "Rådhuspassagen 3, 6600 Vejen",
            email: "info@urvejen.dk"
        },
        {
            id: 20,
            slug: "unternehmensverband-unterelbe-westkuste",
            name: "Unternehmensverband Unterelbe-Westküste e.V.",
            description: "Business association for the Unterelbe-Westküste region in Germany.",
            description_da: "Erhvervsforening for Unterelbe-Westküste-regionen i Tyskland.",
            description_de: "Unternehmensverband für die Region Unterelbe-Westküste in Deutschland.",
            descriptionLong: "Unternehmensverband Unterelbe-Westküste e.V. is a business association representing companies in the Unterelbe-Westküste region, advocating for industry and regional development.",
            descriptionLong_da: "Unternehmensverband Unterelbe-Westküste e.V. er en erhvervsforening, der repræsenterer virksomheder i Unterelbe-Westküste-regionen og varetager industriens og den regionale udviklings interesser.",
            descriptionLong_de: "Der Unternehmensverband Unterelbe-Westküste e.V. ist ein Wirtschaftsverband, der Unternehmen in der Region Unterelbe-Westküste vertritt und sich für Industrie und Regionalentwicklung einsetzt.",
            country: "DE",
            image: "https://imgur.com/fe454om.jpeg",
            website: "www.uvnord.de",
            phone: "+49 4121 4798 0",
            address: "Reichenstraße 23, 25335 Elmshorn",
            email: "info@uvnord.de"
        },
        {
            id: 21,
            slug: "wfg-flensburg-schleswig",
            name: "WFG Flensburg/Schleswig",
            description: "Economic development agency for Flensburg and Schleswig.",
            description_da: "Erhvervsudviklingsorganisation for Flensborg og Slesvig.",
            description_de: "Wirtschaftsförderungsgesellschaft für Flensburg und Schleswig.",
            descriptionLong: "WFG Flensburg/Schleswig is the economic development agency for Flensburg and Schleswig, attracting investment and supporting companies in the Northern Schleswig-Holstein region.",
            descriptionLong_da: "WFG Flensburg/Schleswig er erhvervsudviklingsorganisationen for Flensborg og Slesvig, som tiltrækker investeringer og støtter virksomheder i det nordlige Slesvig-Holsten.",
            descriptionLong_de: "Die WFG Flensburg/Schleswig ist die Wirtschaftsförderungsgesellschaft für Flensburg und Schleswig, die Investitionen anzieht und Unternehmen in der Region Nordschleswig-Holstein unterstützt.",
            country: "DE",
            image: "https://imgur.com/ntybdEK.jpeg",
            website: "www.wfg-fl.de",
            phone: "+49 461 8082 0",
            address: "Lilienthalstraße 1, 24941 Flensburg",
            email: "info@wfg-fl.de"
        },
        {
            id: 22,
            slug: "wfg-rendsburg-eckernforde",
            name: "WFG Rendsburg-Eckernförde",
            description: "Economic development agency for the Rendsburg-Eckernförde district.",
            description_da: "Erhvervsudviklingsorganisation for Rendsburg-Eckernförde-distriktet.",
            description_de: "Wirtschaftsförderungsgesellschaft für den Kreis Rendsburg-Eckernförde.",
            descriptionLong: "WFG Rendsburg-Eckernförde is the economic development agency for the Rendsburg-Eckernförde district, promoting investment and business growth in central Schleswig-Holstein.",
            descriptionLong_da: "WFG Rendsburg-Eckernförde er erhvervsudviklingsorganisationen for Rendsburg-Eckernförde-distriktet, som fremmer investeringer og erhvervsvækst i det centrale Slesvig-Holsten.",
            descriptionLong_de: "Die WFG Rendsburg-Eckernförde ist die Wirtschaftsförderungsgesellschaft für den Kreis Rendsburg-Eckernförde und fördert Investitionen und Unternehmenswachstum im zentralen Schleswig-Holstein.",
            country: "DE",
            image: "https://imgur.com/oBfNsNH.jpeg",
            website: "www.wfg-rd.de",
            phone: "+49 4331 1377 0",
            address: "T-Damm 33, 24768 Rendsburg",
            email: "info@wfg-rd.de"
        },
        {
            id: 23,
            slug: "wfg-nordfriesland",
            name: "WFG Nordfriesland",
            description: "Economic development agency for the Nordfriesland district.",
            description_da: "Erhvervsudviklingsorganisation for Nordfriesland-distriktet.",
            description_de: "Wirtschaftsförderungsgesellschaft für den Kreis Nordfriesland.",
            descriptionLong: "WFG Nordfriesland is the economic development agency for the Nordfriesland district, supporting companies and attracting investment across Germany's northernmost coastal region.",
            descriptionLong_da: "WFG Nordfriesland er erhvervsudviklingsorganisationen for Nordfriesland-distriktet, som støtter virksomheder og tiltrækker investeringer i Tysklands nordligste kystregion.",
            descriptionLong_de: "Die WFG Nordfriesland ist die Wirtschaftsförderungsgesellschaft für den Kreis Nordfriesland und unterstützt Unternehmen und zieht Investitionen in Deutschlands nördlichster Küstenregion an.",
            country: "DE",
            image: "https://imgur.com/FuFhNtW.jpeg",
            website: "www.wfg-nf.de",
            phone: "+49 4841 89 78 0",
            address: "Damm 14, 25813 Husum",
            email: "info@wfg-nf.de"
        },
        {
            id: 24,
            slug: "wirtschaftsvereinigung-eutin",
            name: "Wirtschaftsvereinigung Eutin e.V.",
            description: "Business association supporting companies in Eutin.",
            description_da: "Erhvervsforening, der støtter virksomheder i Eutin.",
            description_de: "Wirtschaftsvereinigung zur Förderung von Unternehmen in Eutin.",
            descriptionLong: "Wirtschaftsvereinigung Eutin e.V. is a business association supporting companies and entrepreneurs in Eutin and the surrounding Ostholstein region.",
            descriptionLong_da: "Wirtschaftsvereinigung Eutin e.V. er en erhvervsforening, der støtter virksomheder og iværksættere i Eutin og den omkringliggende Ostholstein-region.",
            descriptionLong_de: "Die Wirtschaftsvereinigung Eutin e.V. ist ein Wirtschaftsverband, der Unternehmen und Unternehmer in Eutin und der umliegenden Region Ostholstein unterstützt.",
            country: "DE",
            image: "https://imgur.com/aIRO9LU.jpeg",
            website: "www.wv-eutin.de",
            phone: "+49 4521 70 99 0",
            address: "Markt 1, 23701 Eutin",
            email: "info@wv-eutin.de"
        },
        {
            id: 25,
            slug: "work-live-stay",
            name: "Work-live-stay",
            description: "Network attracting and retaining international talent in Southern Denmark.",
            description_da: "Netværk, der tiltrækker og fastholder internationale talenter i Syddanmark.",
            description_de: "Netzwerk zur Gewinnung und Bindung internationaler Talente in Süddänemark.",
            descriptionLong: "Work-live-stay is a network focused on attracting and retaining international talent in Southern Denmark, working with companies, municipalities, and educational institutions across the region.",
            descriptionLong_da: "Work-live-stay er et netværk med fokus på at tiltrække og fastholde internationale talenter i Syddanmark i samarbejde med virksomheder, kommuner og uddannelsesinstitutioner i hele regionen.",
            descriptionLong_de: "Work-live-stay ist ein Netzwerk, das sich auf die Gewinnung und Bindung internationaler Talente in Süddänemark konzentriert und mit Unternehmen, Gemeinden und Bildungseinrichtungen in der gesamten Region zusammenarbeitet.",
            country: "DK",
            image: "https://imgur.com/ajXg2Dk.jpeg",
            website: "www.worklivestay.dk",
            phone: "+45 65 50 22 00",
            address: "Campusvej 55, 5230 Odense M",
            email: "info@worklivestay.dk"
        },
        {
            id: 26,
            slug: "workindenmark-south",
            name: "Workindenmark South",
            description: "Public service helping international workers find jobs in Denmark.",
            description_da: "Offentlig service, der hjælper internationale arbejdstagere med at finde job i Danmark.",
            description_de: "Öffentlicher Dienst, der internationalen Arbeitnehmern hilft, Arbeit in Dänemark zu finden.",
            descriptionLong: "Workindenmark South is the regional office of Denmark's public service helping international workers find jobs in the country and supporting Danish employers with international recruitment.",
            descriptionLong_da: "Workindenmark South er det regionale kontor for Danmarks offentlige service, der hjælper internationale arbejdstagere med at finde job i landet og støtter danske arbejdsgivere med international rekruttering.",
            descriptionLong_de: "Workindenmark South ist das Regionalbüro des öffentlichen Dienstes Dänemarks, das internationalen Arbeitnehmern hilft, Arbeit im Land zu finden, und dänische Arbeitgeber bei der internationalen Personalbeschaffung unterstützt.",
            country: "DK",
            image: "https://imgur.com/5spOyjw.jpeg",
            website: "www.workindenmark.dk",
            phone: "+45 72 22 33 00",
            address: "Dannebrogsgade 3, 5000 Odense C",
            email: "south@workindenmark.dk"
        }
    ])

    const selectedCountry = ref('all')

    const filteredMembers = computed(() => {
        if (selectedCountry.value === 'all') return members.value
        return members.value.filter(m => m.country === selectedCountry.value)
    })

    return {
        members,
        selectedCountry,
        filteredMembers
    }
}