import { ref } from "vue";

export const useNewsCard = () => {
const newsCards = ref ([
    {
      id: 1,
      image: "https://i.imgur.com/AXmyIBs.jpeg",  
      title: "Southern Denmark’s Supercomputer Boost",
      title_da: "Syd Danmarks Supercomputer Boost",
      title_de: "Süd Dänemarks Supercomputer Boost",
      description: "Southern Denmark is making a notable push in advanced computing with the launch of a new AI supercomputer in Sønderborg. The system gives researchers significantly more processing power for data-heavy work such as artificial intelligence, simulation, and complex analysis, which can support both academic research and industrial innovation. The project is especially relevant for business readers because it reflects how regional institutions and major companies like Danfoss are investing in digital infrastructure that can improve competitiveness, energy efficiency, and product development. It also strengthens Southern Denmark’s position as a region where research and industry are closely linked.",
      description_da: "Syd Danmark gør en bemærkelsesværdig indsats inden for avanceret databehandling med lanceringen af en ny AI-supercomputer i Sønderborg. Systemet giver forskere betydeligt mere processorkraft til dataintensive opgaver som kunstig intelligens, simulering og kompleks analyse, hvilket kan støtte både akademisk forskning og industriel innovation. Projektet er især relevant for erhvervslæsere, fordi det afspejler, hvordan regionale institutioner og store virksomheder som Danfoss investerer i digital infrastruktur, der kan forbedre konkurrenceevnen, energieffektiviteten og produktudviklingen. Det styrker også Syd Danmarks position som en region, hvor forskning og industri er tæt forbundet.",
      description_de: "Süd Dänemark macht einen bemerkenswerten Vorstoß im Bereich der Hochleistungsrechner mit der Einführung eines neuen KI-Supercomputers in Sønderborg. Das System bietet Forschern erheblich mehr Rechenleistung für datenintensive Arbeiten wie künstliche Intelligenz, Simulationen und komplexe Analysen, was sowohl die akademische Forschung als auch die industrielle Innovation unterstützen kann. Das Projekt ist besonders relevant für Geschäftsleser, da es zeigt, wie regionale Institutionen und große Unternehmen wie Danfoss in digitale Infrastruktur investieren, die die Wettbewerbsfähigkeit, Energieeffizienz und Produktentwicklung verbessern kann. Es stärkt auch Süd Dänemarks Position als eine Region, in der Forschung und Industrie eng verbunden sind.",
      category: "technology",
      category_da: "teknologi",
      category_de: "Technologie",
      slug: "southern-denmark-supercomputer-boost",
    },
    {
      id: 2,
      image: "https://i.imgur.com/a8vTGvb.jpeg",  
      title: "Germany’s Business Pressure Grows",
      title_da: "Tysklands forretningspres vokser",
      title_de: "Der Druck auf die deutsche Wirtschaft wächst",
      description: "Germany’s business community is continuing to pressure Berlin for faster and more credible economic reforms. The core complaint is that companies are still facing too much uncertainty, high operating costs, and too little momentum on issues such as energy policy, digitalization, tax reform, and labor market flexibility. For a business audience, this story matters because it signals that confidence in Europe’s largest economy remains fragile, even as companies try to plan investment and hiring decisions. The broader message is that the private sector wants the government to act quickly before weak growth becomes more entrenched.",
      description_da: "Tysklands erhvervsliv fortsætter med at presse Berlin for hurtigere og mere troværdige økonomiske reformer. Den centrale klage er, at virksomheder stadig står over for for meget usikkerhed, høje driftsomkostninger og for lidt momentum i spørgsmål som energipolitik, digitalisering, skattereform og fleksibilitet på arbejdsmarkedet. For en erhvervspublikummer er denne historie vigtig, fordi den signalerer, at tilliden til Europas største økonomi forbliver skrøbelig, selv når virksomheder forsøger at planlægge investerings- og ansættelsesbeslutninger. Det bredere budskab er, at den private sektor ønsker, at regeringen handler hurtigt, før svag vækst bliver mere indgroet.",
      description_de: "Die deutsche Wirtschaftsgemeinschaft übt weiterhin Druck auf Berlin aus, um schnellere und glaubwürdigere wirtschaftliche Reformen durchzuführen. Die Hauptbeschwerde ist, dass Unternehmen immer noch mit zu viel Unsicherheit, hohen Betriebskosten und zu wenig Schwung bei Themen wie Energiepolitik, Digitalisierung, Steuerreform und Flexibilität auf dem Arbeitsmarkt konfrontiert sind. Für ein geschäftliches Publikum ist diese Geschichte wichtig, weil sie signalisiert, dass das Vertrauen in Europas größte Volkswirtschaft fragil bleibt, selbst wenn Unternehmen versuchen, Investitions- und Einstellungsentscheidungen zu planen. Die breitere Botschaft ist, dass der private Sektor möchte, dass die Regierung schnell handelt, bevor schwaches Wachstum stärker verankert wird.",
      category: "business",
      category_da: "erhverv",
      category_de: "Geschäft",
      slug: "germany-business-pressure-grows",
    },
    {
      id: 3,
      image: "https://i.imgur.com/gCVYFp2.jpeg",  
      title: "Odense Health Innovation Day",
      title_da: "Odense Sundhedsinnovationsdag",
      title_de: "Odense Gesundheitsinnovationsdag",
      description: "Health Innovation Day 2026 at SDU in Odense is shaping up as an important meeting point for researchers, healthcare professionals, companies, and public-sector partners. The event’s focus is on turning health research into practical solutions, which makes it especially relevant for businesses working in medtech, diagnostics, digital health, and life sciences. It also reflects a broader regional effort to connect universities and industry more effectively so that ideas move faster from concept to implementation. For a business site, the most important angle is the opportunity: this is where partnerships, funding, and commercialization can begin to take shape.",
      description_da: "Sundhedsinnovationsdagen 2026 ved SDU i Odense er under udvikling til et vigtigt mødested for forskere, sundhedsfaglige professionelle, virksomheder og offentlige partnere. Fokus for begivenheden er at omvandele sundhedsforskning til praktiske løsninger, hvilket gør den særligt relevant for virksomheder, der arbejder inden for medtech, diagnostik, digital sundhed og livsvitenskab. Det reflekterer også et bredere regionalt initiativ til at forbinde universiteter og industrien mere effektivt, så ideer bevæger sig hurtigere fra koncept til implementering. For en business hjemmeside er den vigtigste vinkel muligheden: dette er stedet, hvor partnerskaber, finansiering og kommercialisering kan begynde at forme sig.",
      description_de: "Die Gesundheitsinnovationsdag 2026 an der SDU in Odense entwickelt sich zu einem wichtigen Treffpunkt für Forscher, Gesundheitsfachkräfte, Unternehmen und öffentliche Partner. Der Fokus des Events liegt darauf, Gesundheitsforschung in praktische Lösungen umzuwandeln, was sie besonders relevant für Unternehmen macht, die in Medtech, Diagnostik, digitale Gesundheit und Lebenswissenschaften tätig sind. Sie reflektiert auch einen breiteren regionalen Aufwand, um Universitäten und Industrie effektiver zu verbinden, damit Ideen schneller von Konzept zu Umsetzung gelangen. Für eine Geschäftsseite ist der wichtigste Aspekt die Gelegenheit: Hier können Partnerschaften, Finanzierung und Kommerzialisierung beginnen, sich zu formen.",
      category: "health",
      category_da: "sundhed",
      category_de: "Gesundheit",
      slug: "odense-health-innovation-day",
    },
    {
      id: 4,
      image: "https://i.imgur.com/Trlf3Lb.jpeg",  
      title: "Western Germany’s Political Shift",
      title_da: "Tysklands politiske skift",
      title_de: "Der politische Wandel in Westdeutschland",
      description: "The recent state election in Rhineland-Palatinate showed a clear shift in western German politics, with the CDU emerging as the strongest party and the AfD recording its best result in the region so far. That outcome is politically important because western Germany has often been seen as more stable and less vulnerable to the extreme right than some eastern states. The result suggests that economic frustration, migration debates, and dissatisfaction with the status quo are reshaping voter behavior in a major industrial region. For businesses, this kind of change matters because political momentum can affect regulation, labor policy, infrastructure spending, and the overall investment climate.",
      description_da: "Det nylige delstatsvalg i Rheinland-Pfalz viste et klart skift i den vesttyske politik, hvor CDU fremstod som det stærkeste parti, og AfD opnåede sit bedste resultat i regionen hidtil. Det resultat er politisk vigtigt, fordi det vestlige Tyskland ofte er blevet set som mere stabilt og mindre sårbart over for det ekstreme højre end nogle østlige stater. Resultatet antyder, at økonomisk frustration, migrationsdebatter og utilfredshed med status quo omformer vælgeradfærd i en stor industriregion. For virksomheder betyder denne slags ændring noget, fordi politisk momentum kan påvirke regulering, arbejdsmarkedspolitik, infrastrukturudgifter og det overordnede investeringsklima.",
      description_de: "Die jüngste Landtagswahl in Rheinland-Pfalz zeigte eine klare Verschiebung in der westdeutschen Politik, wobei die CDU als stärkste Partei hervorging und die AfD ihr bestes Ergebnis in der Region bisher erzielte. Dieses Ergebnis ist politisch wichtig, weil Westdeutschland oft als stabiler und weniger anfällig für das extreme rechte Spektrum angesehen wurde als einige östliche Bundesländer. Das Ergebnis deutet darauf hin, dass wirtschaftliche Frustration, Migrationsdebatten und Unzufriedenheit mit dem Status quo das Wählerverhalten in einer wichtigen Industrieregion neu gestalten. Für Unternehmen ist diese Art von Veränderung relevant, weil politisches Momentum die Regulierung, Arbeitsmarktpolitik, Infrastrukturinvestitionen und das allgemeine Investitionsklima beeinflussen kann.",
      category: "politics",
      category_da: "politik",
      category_de: "Politik",
      slug: "western-germany-political-shift",
    },
    {
      id: 5,
      image: "https://i.imgur.com/Trlf3Lb.jpeg",  
      title: "SDU Adds Football Research Star",
      title_da: "SDU tilføjer fodboldforskningsstjerne",
      title_de: "SDU holt Fußball-Forschungsstar",
      description: "Southern Denmark’s University of Southern Denmark has strengthened its research profile by appointing Chris Carling, a leading football researcher, to deepen its work in sports science and performance analysis. This is more than a symbolic hire: it points to a growing trend in which universities combine academic research with practical applications in elite sports, analytics, and physical performance. For companies and institutions, the story is relevant because it shows how research talent can feed into innovation ecosystems beyond the lab, including data analysis, training technology, and performance optimization. It also helps position SDU as a competitive research institution with international appeal.",
      description_da: "Den sydøst-danske universitet har styrket sin forskningsprofil ved at tilkende Chris Carling, en ledende fodboldforsker, for at dybe deres arbejde i sportsviden og præstationsanalyse. Dette er mere end en symbolsk ansættelse: det peger på en voksende tendens, hvor universiteter kombinerer akademisk forskning med praktiske anvendelser i elite-sport, analytik og fysisk præstation. For virksomheder og institutioner er historien relevant, fordi den viser, hvordan forskningstalent kan føre til innovationsøkosystemer uden for laboratoriet, herunder dataanalyse, trænings-teknologi og præstationsoptimering. Det hjælper også med at positionere SDU som en konkurrencekraftig forskningsinstitution med international appeal.",
      description_de: "Die Universität des südlichen Dänemarks hat ihre Forschungsprofil durch die Ernennung von Chris Carling, einem führenden Fußball-Forscher, verstärkt, um ihr Arbeit in Sportwissenschaft und Leistungsanalyse zu vertiefen. Dies ist mehr als eine symbolische Anstellung: es deutet auf einen wachsenden Trend hin, bei dem Universitäten akademische Forschung mit praktischen Anwendungen in Elite-Sport, Analytics und physische Leistung kombinieren. Für Unternehmen und Institutionen ist diese Geschichte relevant, weil sie zeigt, wie Forschungstalent in Innovationsökonomien jenseits des Labors einfließen kann, einschließlich Datenanalyse, Trainings-Technologie und Leistungs-Optimierung. Es hilft auch dabei, SDU als wettbewerbsfähige Forschungseinrichtung mit internationaler Attraktivität zu positionieren.",
      category: "science",
      category_da: "videnskab",
      category_de: "Wissenschaft",
      slug: "sdu-adds-football-research-star",
    },
    {
      id: 6,
      image: "https://i.imgur.com/Trlf3Lb.jpeg",  
      title: "Western Germany’s Political Shift",
      title_da: "Tysklands politiske skift",
      title_de: "Der politische Wandel in Westdeutschland",
      description: "The recent state election in Rhineland-Palatinate showed a clear shift in western German politics, with the CDU emerging as the strongest party and the AfD recording its best result in the region so far. That outcome is politically important because western Germany has often been seen as more stable and less vulnerable to the extreme right than some eastern states. The result suggests that economic frustration, migration debates, and dissatisfaction with the status quo are reshaping voter behavior in a major industrial region. For businesses, this kind of change matters because political momentum can affect regulation, labor policy, infrastructure spending, and the overall investment climate.",
      description_da: "Den seneste statsevalg i Rhineland-Palatinate viste en tydelig skift i vesttysk politik, med CDU som den stærkeste parti og AfD som registrerede deres bedste resultat i regionen indtil videre. Denne udfald er politisk vigtig, fordi vesttyskland ofte er blevet set som mere stabil og mindre sårbare for den ekstreme højre end nogle østlige stater. Resultatet antyder, at økonomisk frustration, migration debatter og utilfredshed med status quo er omformning af vælgeradfærd i en stor industri region. For virksomheder er denne type ændring vigtig, fordi politisk impulser kan påvirke regulering, arbejdspolitik, infrastruktur udgifter og det samlede investeringsklima.",
      description_de: "Die kürzliche Landtagswahl in Rheinland-Pfalz zeigte einen klaren Wandel in der westdeutschen Politik, wobei die CDU als stärkste Partei hervortritt und die AfD ihren besten Ergebnis in der Region bisher aufzeichnet. Dieser Ausgang ist politisch wichtig, da Westdeutschland oft als stabiler und weniger anfällig für die extreme Rechte angesehen wurde als einige ostdeutsche Länder. Das Ergebnis deutet darauf hin, dass wirtschaftliche Frustration, Migrationsdebatten und Unmut gegenüber dem Status Quo das Wählerverhalten in einer großen Industrie-Region verändern. Für Unternehmen ist diese Art von Veränderung wichtig, da politischer Impuls Auswirkungen auf Regulierung, Arbeitspolitik, Infrastrukturinvestitionen und das gesamte Investitions-Klima haben kann.",
      category: "politics",
      category_da: "politik",
      category_de: "Politik",
      slug: "western-germany-political-shift",
    },
    {
      id: 7,
      image: "https://i.imgur.com/Trlf3Lb.jpeg",  
      title: "SDU Boosts Football Research",
      title_da: "SDU styrker fodboldforskning",
      title_de: "SDU verstärkt Fußball-Forschung",
      description: "SDU’s decision to bring in Chris Carling, an internationally recognized football researcher, signals a stronger emphasis on data-driven sports performance. Modern football increasingly depends on analytics, biomechanics, recovery science, and evidence-based training, so this appointment fits a wider industry shift toward measurable performance gains. From a business perspective, the story matters because sports science is becoming a commercial field with links to software, wearable technology, coaching systems, and elite athlete development. It also gives SDU a sharper profile in a sector where research can quickly translate into practical value.",
      description_da: "SDU’s beslutning om at tiltrække Chris Carling, en internationalt anerkendt fodboldforsker, signalerer en stærkere fokus på data-drevet sportsspecifik præstation. Moderne fodbold afhænger yderligere af analysering, biomekanikker og genopretningsvidenskab samt evidensbaserede træningsmetoder. Dermed passer denne ansættelse ind i en bredere brancheudvikling mod målbare præstationsforbedringer. Fra et forretningsperspektiv er historien vigtig fordi sportsviden bliver til et kommercialiseret felt med forbindelser til softwareløsninger og bærbare teknologier samt trænings-systemer og udvikling af elite-athleter.",
      description_de: "Die Entscheidung von SDU, Chris Carling einzustellen – einen international anerkannten Fußball-Forscher – signalisiert einen stärkeren Fokus auf datengestützte Sportleistung. Moderne Fußball hängt zunehmend von Analytics ab sowie Biomechanik und Erholungs-Wissenschaften und evidenzbasierte Trainingsmethoden; daher passt diese Ernennung in eine breitere Branchentrendrichtung hin zu messbaren Leistungsverbesserungen. Aus einer Geschäftsperspektive ist diese Geschichte wichtig weil Sportwissenschaft zu einem kommerziellen Bereich wird mit Verbindungen zu Softwarelösungen sowie tragbaren Technologien und Trainingsystemen sowie zur Entwicklung von Elite-Athleten.",
      category: "sports",
      category_da: "sport",
      category_de: "Sport",
      slug: "sdu-boosts-football-research",
    },
    {
      id: 8,
      image: "https://i.imgur.com/Trlf3Lb.jpeg",  
      title: "Tønder Festival Stays Strong",
      title_da: "Tønder Festival forbliver stærk",
      title_de: "Tønder Festival bleibt stark",
      description: "Tønder Festival remains one of Southern Denmark’s most recognisable cultural events, and its continuing presence matters well beyond music fans. Festivals like this support hotels, restaurants, transport, retail, and local tourism, while also helping shape the region’s identity and visibility. For a business audience, the story is interesting because cultural events are not just entertainment; they are part of the local economy and can have a real effect on foot traffic and seasonal spending. Tønder also helps Southern Denmark maintain a strong cultural brand that can attract visitors and reinforce regional appeal.",
      description_da: "Tønder Festival forbliver en af Syd-Danmarks mest genkendelige kulturelle begivenheder, og dens fortsatte tilstedeværelse har betydning langt uden for musikfans. Fester som denne støtter hoteller, restauranter, transport, detailhandel og lokal turisme, samtidig med at de også hjælper med at forme regionens identitet og synlighed. For en virksomhedsmæssig målgruppe er historien interessant fordi kulturelle begivenheder ikke kun er underholdning; de er en del af den lokale økonomi og kan have en reel effekt på fods traffic og sæsonel udgift. Tønder hjælper også Syd-Danmark med at bevare et stærkt kulturelt brand, der kan tiltrække besøgende og styrke regional attraktivitet.",
      description_de: "Tønder Festival bleibt eine der erkennbarsten kulturellen Veranstaltungen in Süddänemark, und ihre fortlaufende Präsenz hat Bedeutung weit über Musikkäufer hinaus. Festivals wie diese unterstützen Hotels, Restaurants, den Verkehr, den Einzelhandel und den lokalen Tourismus und helfen gleichzeitig dabei, die Identität und Sichtbarkeit der Region zu prägen. Für eine Geschäftsperspektive ist diese Geschichte interessant weil kulturelle Veranstaltungen nicht nur Unterhaltung sind; sie sind Teil der lokalen Wirtschaft und können einen echten Effekt auf den Fußverkehr und saisonale Ausgaben haben. Tønder hilft auch Süddänemark dabei, ein starkes kulturelles Brand zu bewahren, das Besucher anziehen und die regionale Attraktivität stärken kann.",
      category: "culture",
      category_da: "kultur",
      category_de: "Kultur",
      slug: "tonder-festival-stays-strong",
    },
]);

    return {
        newsCards
    }
}